module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
      default: ['Space Mono', 'monospace'],
    },
    extend: {
      colors: {
        strong_cyan: '#26c0ab',
        very_dark_cyan: '#00494d',
        dark_grayish_cyan: '#5e7a7d',
        dark_greyish_cyan: '#7f9c9f',
        light_grayish_cyan: '#c5e4e7',
        light_greyish_cyan: '#f4fafa',
        white: '#ffffff',
      },
    },
  },
  plugins: [],
};
